apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  namespace: appsody-project
  name: app-spring
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker-registry.default.svc:5000/appsody-project/app-spring
            imagePullPolicy: Always
            ports:
            - containerPort: 8080