apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: app-spring
spec:
  stack: java-spring-boot2
  applicationImage: timrodocker/app-spring:v0.1
  pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  expose: true
